[0m11:26:50.421826 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10e1298e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10e198c80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10e808b30>]}


============================== 11:26:50.427931 | 376acda8-eeed-4edc-8dda-8b197a6ee14e ==============================
[0m11:26:50.427931 [info ] [MainThread]: Running with dbt=1.8.5
[0m11:26:50.428768 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': '/Users/admin/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt init OlympicAnalysis', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m11:26:50.456700 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse dict {'dir': PosixPath('/Users/admin/.dbt')}
[0m11:26:50.457585 [info ] [MainThread]: Creating dbt configuration folder at 
[0m11:26:50.460610 [debug] [MainThread]: Starter project path: /Users/admin/Desktop/Development/ELT-pipeline-olympic-dataset/.dbtenv/lib/python3.12/site-packages/dbt/include/starter_project
[0m11:26:50.481591 [info ] [MainThread]: 
Your new dbt project "OlympicAnalysis" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m11:26:50.482403 [info ] [MainThread]: Setting up your profile.
[0m11:27:33.138235 [debug] [MainThread]: Spark adapter: Setting pyhive.hive logging to ERROR
[0m11:27:33.139439 [debug] [MainThread]: Spark adapter: Setting thrift.transport logging to ERROR
[0m11:27:33.139869 [debug] [MainThread]: Spark adapter: Setting thrift.protocol logging to ERROR
[0m11:35:26.907080 [error] [MainThread]: Encountered an error:

[0m11:35:26.966403 [error] [MainThread]: Traceback (most recent call last):
  File "/Users/admin/Desktop/Development/ELT-pipeline-olympic-dataset/.dbtenv/lib/python3.12/site-packages/dbt/cli/requires.py", line 138, in wrapper
    result, success = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/admin/Desktop/Development/ELT-pipeline-olympic-dataset/.dbtenv/lib/python3.12/site-packages/dbt/cli/requires.py", line 101, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/admin/Desktop/Development/ELT-pipeline-olympic-dataset/.dbtenv/lib/python3.12/site-packages/dbt/cli/main.py", line 470, in init
    results = task.run()
              ^^^^^^^^^^
  File "/Users/admin/Desktop/Development/ELT-pipeline-olympic-dataset/.dbtenv/lib/python3.12/site-packages/dbt/task/init.py", line 347, in run
    self.setup_profile(profile_name)
  File "/Users/admin/Desktop/Development/ELT-pipeline-olympic-dataset/.dbtenv/lib/python3.12/site-packages/dbt/task/init.py", line 263, in setup_profile
    self.create_profile_from_target(adapter, profile_name=profile_name)
  File "/Users/admin/Desktop/Development/ELT-pipeline-olympic-dataset/.dbtenv/lib/python3.12/site-packages/dbt/task/init.py", line 180, in create_profile_from_target
    self.create_profile_from_profile_template(profile_template, profile_name)
  File "/Users/admin/Desktop/Development/ELT-pipeline-olympic-dataset/.dbtenv/lib/python3.12/site-packages/dbt/task/init.py", line 164, in create_profile_from_profile_template
    target = self.generate_target_from_input(prompts, initial_target)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/admin/Desktop/Development/ELT-pipeline-olympic-dataset/.dbtenv/lib/python3.12/site-packages/dbt/task/init.py", line 130, in generate_target_from_input
    target[key] = click.prompt(
                  ^^^^^^^^^^^^^
  File "/Users/admin/Desktop/Development/ELT-pipeline-olympic-dataset/.dbtenv/lib/python3.12/site-packages/click/termui.py", line 164, in prompt
    value = prompt_func(prompt)
            ^^^^^^^^^^^^^^^^^^^
  File "/Users/admin/Desktop/Development/ELT-pipeline-olympic-dataset/.dbtenv/lib/python3.12/site-packages/click/termui.py", line 147, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m11:35:27.011124 [debug] [MainThread]: Resource report: {"command_name": "init", "command_wall_clock_time": 516.6741, "process_user_time": 1.914878, "process_kernel_time": 0.593774, "process_mem_max_rss": "86597632", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m11:35:27.020193 [debug] [MainThread]: Command `dbt init` failed at 11:35:27.019118 after 516.68 seconds
[0m11:35:27.023639 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10ec47080>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10ebae060>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10ebada30>]}
[0m11:35:27.028505 [debug] [MainThread]: Flushing usage events
